# fly.toml file generated for appe-with-db on 2023-01-04T23:47:27+07:00

app = "appe-with-db"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "yarn db:sync"

[env]
  DATABASE_URL = "postgres://postgres:MM1dbekiIXFr8Yf@appe-with-db-db.internal:5432"
  PORT = "8080"
  JWT_ACCESS_SECRET="ecommers_secret_168"
  JWT_REFRESH_SECRET="ecommerse_secret_168"
  SUPER_ADMIN_EMAIL="ecommers@dev.com"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
